### ISSUE TITLE
2d myocardial strain

### ISSUE THREAD

**Issue by Hello-Worldd** [cshennju/NeuralCMF#3]
Thank you for your work！
Can you share the code of **2d myocardial strain test** based on NeuralCMF？
Thank you！

**Comment by cshennju** [comment]
Our method is specifically designed to accurately estimate the 3D motion of each point within the heart by utilizing 3D echocardiogram videos or specifically multi-angle 2D echocardiogram videos, rather than conventional 2D echocardiogram videos. You can understand it as our approach first reconstructs a 3D heart using multi-angle 2D echocardiogram videos, and then performs precise 3D motion estimation based on this reconstructed model.
